### ISSUE TITLE
Add all colors for `has-background`

### ISSUE THREAD

**Issue by jzelez** [shirohana/bulma.stylus#5]
Currently only `$shades` are implemented.

```stylus
for $name, $pair in $colors
  $color = $pair[0]
  .has-text-{$name}
    color: $color !important
  a.has-text-{$name}
    &:hover
    &:focus
      color: sass-darken($color, 10%) !important
  .has-background-{$name}
      background-color: $color !important
```

**Comment by shirohana** [comment]
So you think the background should also darker when hovering? 🤔

I'll create a demo for this

**Comment by jzelez** [comment]
Look at the original implementation here: https://github.com/jgthms/bulma/blob/master/sass/base/helpers.sass#L97

This should be direct stylus port:
```stylus
for $name, $pair in $colors
  $color = $pair[0]
  .has-text-{$name}
    color: $color !important
  a.has-text-{$name}
    &:hover
    &:focus
      color: sass-darken($color, 10%) !important
  .has-background-{$name}
      background-color: $color !important

for $name, $shade in $shades
  .has-text-{$name}
    color: $shade !important
  .has-background-{$name}
    background-color: $shade !important
```

**Comment by shirohana** [comment]
The link you pasted is an old version :(

https://github.com/jgthms/bulma/blob/master/sass/base/helpers.sass#L97-L112

Current stylus implementation:
```stylus
for $name, $pair in $colors
  $color = $pair[0]
  .has-text-{$name}
    color: $color !important
  a.has-text-{$name}
    &:hover
    &:focus
      color: sass-darken($color, 10%) !important
  .has-background-{$name}
    background-color: $color

for $name, $shade in $shades
  .has-text-{$name}
    color: $shade !important
  .has-background-{$name}
    background-color: $shade !important
```

**Comment by jzelez** [comment]
Sorry 'bout that. I've updated my comment above.

**Comment by shirohana** [comment]
I just complete an example about your problem, I think let the background darker is not a good idea, we don't need a large anchor block with bright color normally :(

https://codepen.io/shirohana/pen/BxaZKW?editors=1100

**Comment by shirohana** [comment]
By the way, I think you should move this issue to [jgthms/bulma](https://github.com/jgthms/bulma), it's not related to a stylus implementation of Bulma (´-ωก`)

**Comment by jzelez** [comment]
I'm not talking about any issue or darker colors...   Just about missing `has-background-...` in bulma.stylus.

**Comment by shirohana** [comment]
I can't get your point (´⊙ω⊙`)

![2018-04-18 8 39 23](https://user-images.githubusercontent.com/11359892/38932421-b5e52948-4348-11e8-8ff0-84037c217b17.png)

**Comment by shirohana** [comment]
Isn't it mean you expect there's a background-color on `a.has-background-{$name}` (´・ω・｀)？

There's already has `.has-background-{$name}` on no specified element, so...

```stylus
for $name, $pair in $colors
  $color = $pair[0]
  .has-background-{$name}
    background: $color !important
> a.has-background-{$name}
>   &:hover
>   &:focus
>     background: sass-darken($color, 10%) !important
```

**Comment by jzelez** [comment]
Hm.. you're right. I've reinstalled the package and now I see it. Weird. 
Sorry for the confusion.
