### ISSUE TITLE
$control-border-width

### ISSUE THREAD

**Issue by jzelez** [shirohana/bulma.stylus#6]
Hi! I'm getting undefined margin-left in `.button .icon`.

<img width="527" alt="screenshot 2018-04-23 11 01 11" src="https://user-images.githubusercontent.com/386099/39116845-b6a17990-46e5-11e8-8107-4c5cbf6b276e.png">

**Comment by shirohana** [comment]
Which `@shirohana/bulma-stylus` version you used?

The `element/button.styl` uses the variable from `utilities/controls.styl`, ensure you've already imported them.

```stylus
@import "@shirohana/bulma-stylus/stylus/utilities"
// or
@import "@shirohana/bulma-stylus/stylus/utilities/control"
```

https://github.com/jgthms/bulma/blob/master/sass/elements/button.sass#L5

**Comment by jzelez** [comment]
True... my mistake, I didn't load `controls.styl`.
